spring.application.name=application


flag=nosql

#Database info

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true



#-Dspring.profiles.active="prod" - Add this into VM Option to activative specific profile
# spring.profiles.active = qa,prod - can define both profile
# More priority is given to -Dspring.profiles.active="prod" as compared to application.properties

#spring.profiles.active = prod
