spring.application.name=application


flag=nosql


#-Dspring.profiles.active="prod" - Add this into VM Option to activative specific profile
# spring.profiles.active = qa,prod - can define both profile
# More priority is given to -Dspring.profiles.active="prod" as compared to application.properties

spring.profiles.active = prod
